# Sparsity ratios
TARGET_SPARSITY_LOW = 0.95
TARGET_SPARSITY_MID = 0.97
TARGET_SPARSITY_HIGH = 0.99

# Batch Sizes
BATCH_SIZE_CNN = 512
BATCH_SIZE_VIT = 256
BATCH_SIZE_LLM = 64

# Epochs
EPOCHS_SMALL_MODEL = 100
EPOCHS_LARGE_MODEL = 150
EPOCHS_VIT = 10
